### ISSUE TITLE
Named unicode escapes with spaces marked as syntax error in f-strings

### ISSUE THREAD

**Issue by bryanforbes** [davidhalter/parso#154] opened 2020-10-10 02:14 UTC
Given the following code:

```python
def bullet(text: str) -> str:
    return f'\N{BULLET} {text}'


def error(text: str) -> str:
    return f'\N{NO ENTRY} {text}'
```

A syntax error is marked for `ENTRY` but it is valid Python code.

**Comment by davidhalter** [comment] 2020-10-10 08:31
I think parso understands this as two f-string inputs, which is wrong.

Though I have to say that this is another one of these WTFs.

**Comment by isidentical** [comment] 2020-10-10 11:18
It looks like we are tokenizing it correctly;
```
TokenInfo(type=FSTRING_START, string="f'", start_pos=(2, 11), prefix=' ')
TokenInfo(type=FSTRING_STRING, string='⛔ ', start_pos=(2, 13), prefix='')
TokenInfo(type=OP, string='{', start_pos=(2, 15), prefix='')
TokenInfo(type=NAME, string='text', start_pos=(2, 16), prefix='')
TokenInfo(type=OP, string='}', start_pos=(2, 20), prefix='')
TokenInfo(type=FSTRING_END, string="'", start_pos=(2, 21), prefix='')
```

**Comment by isidentical** [comment] 2020-10-10 11:20
I can't reproduce the error with this
```py
import parso

def _get_error_list(code, version=None):
    grammar = parso.load_grammar(version=version)
    tree = grammar.parse(code)
    return list(grammar.iter_errors(tree))

source = """\
def bullet(text: str) -> str:
    return f'\N{BULLET} {text}'


def error(text: str) -> str:
    return f'\N{NO ENTRY} {text}'
"""    

print(_get_error_list(source))
```
```
 $ python t.py                
[]
```

**Comment by bryanforbes** [comment] 2020-10-10 14:07
You can reproduce it with the following:

```python
import parso

def _get_error_list(code, version=None):
    grammar = parso.load_grammar(version=version)
    tree = grammar.parse(code)
    return list(grammar.iter_errors(tree))

source = """\
def bullet(text: str) -> str:
    return f'\\N{BULLET} {text}'


def error(text: str) -> str:
    return f'\\N{NO ENTRY} {text}'
"""    

print(_get_error_list(source))
```

The `\N` has to be escaped (`\\N`) in the source string. Once you escape `\N` in the source string, the error shows up.

**Comment by isidentical** [comment] 2020-10-10 17:50
I guess we could potentially patch the regexes with this;
```diff
diff --git a/parso/python/tokenize.py b/parso/python/tokenize.py
index 6282275..bfd8cca 100644
--- a/parso/python/tokenize.py
+++ b/parso/python/tokenize.py
@@ -111,8 +111,8 @@ def _get_token_collection(version_info):
         return result
 
 
-fstring_string_single_line = _compile(r'(?:\{\{|\}\}|\\(?:\r\n?|\n)|[^{}\r\n])+')
-fstring_string_multi_line = _compile(r'(?:[^{}]+|\{\{|\}\})+')
+fstring_string_single_line = _compile(r'(?:\\N\{[\w ]*\}|\{\{|\}\}|\\(?:\r\n?|\n)|[^{}\r\n])+')
+fstring_string_multi_line = _compile(r'(?:[^{}]+\\N\{[\w ]*\}|[^{}]+|\{\{|\}\})+')
 fstring_format_spec_single_line = _compile(r'(?:\\(?:\r\n?|\n)|[^{}\r\n])+')
 fstring_format_spec_multi_line = _compile(r'[^{}]+')
 
@@ -353,7 +353,7 @@ def _print_tokens(func):
     return wrapper
```
but I don't think this is an elegant approach. Will look into how we could potentially make this better (btw the regex change is untested, but I don't think there would be too many problems regarding that except some trailing ws)

**Comment by bryanforbes** [comment] 2020-10-10 19:44
Shouldn't it be `\\N\{[\w+ ]+\w\}`?

**Comment by davidhalter** [comment] 2020-10-23 16:06
@isidentical I would probably also be ok with the regex solution.

**Comment by isidentical** [comment] 2020-10-23 16:29
If it is urgent, we can proceed with it but I am pretty booked up this month. Hopefully, I'll be able to look into this by the november. Maybe even start drafting some work on migrating to a PEG parser (the `pegen`, underlying parser generator for python, will be released on the PyPI soon-ish with a python backend). I will just draft with using our underlying CST nodes, ofc there won't be error-recovery for the timebeing, what who knows maybe we can hack into it something. (as I said, just an experiment)

**Comment by davidhalter** [comment] 2020-10-23 18:28
Not urgent at all IMO.

**Comment by isidentical** [comment] 2020-11-12 20:08
I did a little bit of playing, but honestly, this is simplest it gets (at least what I observed). @bryanforbes would you like to make a PR? I didn't test that regex much, so it might be problematic but that diff should help you about where to change.

**Closed** 2020-11-22 12:37 UTC
Labels: bug
