### ISSUE TITLE
Example use of refactor / RefactoringNormalizer

### ISSUE THREAD

**Issue by vtjeng** [davidhalter/parso#174] opened 2021-02-20 03:37 UTC
Do you have an example of the `refactor` function or the `RefactoringNormalizer` in use? I've tried searching in GitHub for examples ([`RefactoringNormalizer`](https://github.com/search?l=Python&q=RefactoringNormalizer&type=code), [`parso refactor`](https://github.com/search?l=Python&q=parso+refactor&type=Code)) but all that seems to come up is copies of your source code that others have included in their repos.

(I've read #67, but figured I should start a new thread with a more accurate title).

---

My specific use case is that I'd like to delete a particular named function from my code. Here's what I've come up with 

```
class FunctionHidingNormalizer(Normalizer):
    """
    Hides any of the listed functions when `walk` is called on the normalizer.
    """
    def __init__(self, functions_names_to_hide):
        self.function_names_to_hide = function_names_to_hide

    def visit(self, node):
        if node.type == "funcdef" and node.name.value in self.function_names_to_hide:
            return ""
        return super().visit(node)
```

Calling `FunctionHidingNormalizer(function_names).walk(parso.parse(src))` mostly works, but it doesn't seem to appropriately handle functions with decorators.

**Comment by davidhalter** [comment] 2021-02-20 09:58
Duplicate of #165.

For now please read the code and maybe contribute the documentation. I probably won't do it.

**Closed by davidhalter** 2021-02-20 09:58 UTC

**Comment by davidhalter** [comment] 2021-02-20 10:01
IMO it's pretty obvious what happens if you read the code: A `Dict[NodeOrLeaf, str]` that goes through the tree and replaces all nodes in the dict with strings and leaves all other nodes in the shape that they were.

**Comment by isidentical** [comment] 2021-02-20 10:09
> Calling FunctionHidingNormalizer(function_names).walk(parso.parse(src)) mostly works, but it doesn't seem to appropriately handle functions with decorators.

The decorated functions use the tree symbol 'decorated', so you also have to handle it (just like how you handle 'funcdef'). For the rest of the symbols, you can check the grammar or use `parso.parse()` to figure out what kind of CST structure it has.

**Comment by vtjeng** [comment] 2021-02-21 20:47
Thanks @isidentical - that worked well enough for me. 

@davidhalter, that makes sense. Thanks for pointing me to the duplicate. Just wanted to make sure I wasn't reinventing the wheel. (It looks like, as `RefactoringNormalizer` is currently written, I would have to write my own normalizer, since it can't apply a function to the `NodeOrLeaf`, but instead has to have all the information beforehand in the `Dict`.)

**Comment by davidhalter** [comment] 2021-02-21 21:54
@vtjeng I don't think so, but maybe I don't quite understand.
