### ISSUE TITLE
<TAB> autocomplete stops working for objects with customized __dir__() and __getattr__()

### ISSUE THREAD

**Issue by wyzhao** [davidhalter/parso#82] opened 2019-08-12 20:48 UTC
Environments:
jedi                          0.13.1   
jupyter                       1.0.0    
jupyter-client                5.2.3    
jupyter-console               5.2.0    
jupyter-core                  4.4.0    
jupyterlab                    1.0.5    
jupyterlab-server             1.0.0    
parso                         0.5.0    or 0.5.1	
python                        3.6.2

The object's attributes are shown as "module" and therefore lose the ability to do <TAB> completion.

If I downgrade to parso 0.4, it works fine.

**Comment by davidhalter** [comment] 2019-08-12 22:03
Please upgrade to jedi 0.15.0 and retry. Pretty sure this is not a Jedi issue, I'm also pretty sure Jedi  0.13.1 is incompatible with 0.5.0. So I'm closing, because you are not using the latest versions.

**Closed by davidhalter** 2019-08-12 22:03 UTC

**Comment by wyzhao** [comment] 2019-08-12 23:31
Thank you for the quick reply.
I have upgraded to jedi==0.15.0 and parso==0.5.0, but I cannot <TAB> complete with any package variables, let alone custom objects. This could be due to IPython or Jupyter. I will just downgrade to parso 0.4.0 in the mean time.

**Comment by davidhalter** [comment] 2019-08-13 20:07
No idea why it should b parso. Also, these versions are not compatible. I'm pretty sure it's not a parso issue. It's probably a Jedi issue. If you want to help, open an issue in Jedi with the exact reproduction steps

**Comment by wyzhao** [comment] 2019-08-14 23:22
Thanks, David.
I have identified the problem and created a ticket for ipython team:
https://github.com/ipython/ipython/issues/11856
