### ISSUE TITLE
Issue with the diff parser in update

### ISSUE THREAD

**Issue by blueyed** [davidhalter/parso#45] opened 2018-07-08 22:22 UTC
Just have seen this:

```
[deoplete] Traceback (most recent call last):                          
  File "/home/user/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 229, in _gather_results
    ctx['candidates'] = source.gather_candidates(ctx)                                                           
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 39, in wrapper
    ret = func(self, *args, **kwargs)                                                                                           
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 124, in gather_candidates
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 39, in wrapper  
    ret = func(self, *args, **kwargs)                                                                                           
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 92, in get_completions
    # TODO: skip creating Script instances if not necessary.                                                                   
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 120, in __init__
    cache_path=settings.cache_directory                                                                                            
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/__init__.py", line 383, in parse_and_get_code
    return self.grammar.parse(code=code, path=path, **kwargs), code                                                                               
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/grammar.py", line 76, in parse
    return self._parse(code=code, **kwargs)                                                                                 
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/grammar.py", line 126, in _parse
    new_lines=lines                                                                                                           
  File "/home/user/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/parso/parso/python/diff.py", line 162, in update
    % (last_pos, line_length, ''.join(diff))                                                                                      
Exception: There's an issue (294 != 293) with the diff parser. Please report:
---                                                                          
+++ 
@@ -102,7 +102,6 @@
                                filename,
                                environment=self._env).completions()
                                                                    
-    @profiler.profile
     @profiler.profile
     def massage_completions(self, completions):
         out = []                               
@@ -291,5 +290,4 @@
                     i -= 1
             return self.completion_dict(name, type_, comp)
                                                           
-        return self.completion_dict(name, type_, comp)
-    +        return self.completion_dict(name, type_, comp)
```

Maybe it is related to providing source together with an outdated (because currently being edited) filename?

**Comment by davidhalter** [comment] 2018-07-09 18:57
Latest version? I just found a pretty significant bug and fixed it (latest parso master). This bug looked very similar to what you're having here. (It also had to do with decorators and newlines at the end of a file). See also https://github.com/davidhalter/jedi/issues/1132.

Generally I'm very happy to receive these. However since I think this one is fixed, I'm closing it. Let me know if you have a reproduction case or this happens again with the latest release (just did one), please let me know.

**Closed by davidhalter** 2018-07-09 18:57 UTC

**Comment by blueyed** [comment] 2018-07-10 10:33
Yes, I was using the commit before 52e3db4 very likely.
Thanks!
