### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [davidhalter/parso#200] opened 2021-10-29 15:05 UTC
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/parso/lokal -name '*.py')
```

How do you think about to improve six source code places? :thinking:

-----

:crystal_ball: How would a corresponding refactoring be achieved by the means of the software “parso”?

**Comment by davidhalter** [comment] 2021-10-30 07:25
SorryI don't understand at all. Your regex is quite complicated and I do not understand at all what you're trying to do.

**Comment by elfring** [comment] 2021-10-30 08:25
* Would you dare to try an adjusted Perl command variant out on the source files in another test repository?
* How do you think about to support any collateral evolution according to information from [the Python enhancement proposal 577](https://www.python.org/dev/peps/pep-0577/ "Augmented assignment expressions") (from 2018-05-14)?

**Comment by davidhalter** [comment] 2021-10-30 13:52
I still do not understand at all what you want to change about parso. (Or in general what you want).

I also do not understand why you mention PEP 577, especially since it has been withdrawn.

**Comment by davidhalter** [comment] 2021-10-30 13:54
And BTW: I don't waste my time reading perl, so please explain what you want.

**Comment by elfring** [comment] 2021-10-30 14:00
Can you accept [the explanation from the Python documentation](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") (which seems to present other information about the mentioned status “withdrawn”)?

“…
In the augmented version, `x` is only evaluated once. Also, when possible, the actual operation is performed _in-place_, meaning that rather than creating a new object and assigning that to the target, the old object is modified instead.
…”

:thought_balloon: Do you accordingly expect positive effects for the software run time characteristics?

**Comment by davidhalter** [comment] 2021-10-30 14:35
Sorry I'm closing, I still do not understand at all what your goals are. I understand perfectly what `Augmented assignment statements` are. They are parsed by parso. But now what?

> Do you accordingly expect positive effects for the software run time characteristics?

What does this question have to do with parso?

**Closed by davidhalter** 2021-10-30 14:35 UTC

**Comment by elfring** [comment] 2021-10-30 14:56
>…, I still do not understand at all what your goals are. …

I propose to care a bit more about [information from the release of the software “Python 2.0”](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments").


>But now what?

Assignments can hopefully be found also with the help of your software library.
Does it support already to convert selected statements into augmented variants? :thinking:


>What does this question have to do with parso?

:thought_balloon: Do any factors hinder the wider application of functionality which became generally available with Python 2?

**Comment by davidhalter** [comment] 2021-10-30 15:58
I don't know how experienced you are with Open Source issue trackers, but I assume you are not. Please do not waste maintainer time with questions that are not clear. You should read https://stackoverflow.com/help/minimal-reproducible-example which probably will help you.

About your questions: Jedi and Parso are not Linters, which is probably what you are looking for. Of course these kind of constructs can kind of be found with parso, but I doubt that there's a general way to find these and IMO it's also worthless. It's like most linters. They will find a lot of "noise". If you want to improve performance for Python this is definitively not something that is worth mentioning. You should probably at that point start profiling.

In general your question reminds me a lot about the old tale of "premature optimization". Feel free to look it up, it's still very relevant today :).

**Comment by elfring** [comment] 2021-10-30 16:13
>…, but I assume you are not.

I guess that you can eventually get a more constructive impression from my published software development activities.


>Jedi and Parso are not Linters,

I know also this fact.


>which is probably what you are looking for.

Your software supports also source code transformations to some degree, doesn't it?


>Of course these kind of constructs can kind of be found with parso,

Thanks for such an acknowledgement.


>but I doubt that there's a general way to find these and IMO it's also worthless.

I wonder about such a view.


>They will find a lot of "noise".

This can happen.


>If you want to improve performance for Python this is definitively not something that is worth mentioning. You should probably at that point start profiling.

:thought_balloon: How do you think about to measure the influence of questionable assignments on the run time characteristics for your software components?

**Comment by davidhalter** [comment] 2021-10-30 17:44
Sorry, I don't have time any more for this kind of conversation.
